<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<ul>
    <li>List1</li>
    <li>List2</li>
    <li>List3</li>
</ul>
<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
    "*":{
        "Magento_Ui/js/core/app":{
            "components": {
                 "todo": {
                      "component":"MageMastery_Todo/js/view/todo",
                      "template":"MageMastery_Todo/todo"

                     }
                 }
            }
        }
    }
</script>
